import type { Metadata } from "next";
import "@/styles/globals.css";
import layoutStyle from '@/styles/layout.module.css'
import ReduxProvider from "@/api/providers/ReduxProvider";
import ReactQueryProvider from "@/api/providers/ReactQueryProvider";
import Header from "@/components/Header";
import CategoryBar from "@/components/CategoryBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/favicon.ico",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <ReduxProvider>
          <ReactQueryProvider>
            <div className={layoutStyle.authLayout}>
              {children}
            </div>
          </ReactQueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
