import type { Metadata } from "next";
import "@/styles/globals.css";
import ReduxProvider from "@/api/providers/ReduxProvider";
import ReactQueryProvider from "@/api/providers/ReactQueryProvider";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/favicon.ico",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
        <html lang="ko">
          <body>
            <ReduxProvider>
              <ReactQueryProvider>
                <Header/>
                {children}
              </ReactQueryProvider>
          </ReduxProvider>
          </body>
        </html>
  );
}
