import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/api/providers/ReduxProvider";
import ReactQueryProvider from "@/api/providers/ReactQueryProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
        <html>
          <body>
            <ReduxProvider>
              <ReactQueryProvider>
                {children}
              </ReactQueryProvider>
          </ReduxProvider>
          </body>
        </html>
  );
}
